root = "."
tmp_dir = "build"

[build]
full_bin = "go build -o ./build/main ./cmd/web/ && ./build/main"
cmd = "go build -o ./build/main ./cmd/web/"

# The command to run your application.
bin = "./cmd/web"

# Watch these file extensions.
include_ext = ["go", "tpl", "html", "css"]

# Ignore these directories.
exclude_dir = ["assets", "vendor", "tmp"]

[log]
# Show logs in color.
color = true
